### ISSUE TITLE
Load failures in HIC

### ISSUE THREAD

**Issue by jas88** [SMI/RdmpDicom#330]
|Mutilate failed on job Rdmp.Core.DataLoad.Engine.Job.DataLoadJob Mutilator was of type PrimaryKeyCollisionIsolationMutilation see InnerException for specifics|System.Exception: Supplemental (2 column) joins are not supported when resolving multi table primary key collisions
   at Rdmp.Dicom.PipelineComponents.PrimaryKeyCollisionIsolationMutilation.BuildJoinOrder(Boolean isChecks)
   at Rdmp.Dicom.PipelineComponents.PrimaryKeyCollisionIsolationMutilation.Mutilate(IDataLoadJob job)

**Comment by jas88** [comment]
Resolved - RDMP has to be set up with _right_ joins between study-series-instance, otherwise the manually-cascaded deletion process trips itself up.
